# Programming Assignment 1 - KNN, K-FOLD CV Implementation
## Course: CSE-6363-004 MACHINE LEARNING
## Name: FAHAD UR RAHAMAN
## Student ID: 1001753107
## Email: fahadur.rahaman@mavs.uta.edu
### Please pip install Numpy and Pandas
### Please visit the Report for more detailed explanation and for comparison of KNN, K-Fold CV Implementaion results in WEKA

In [1]:
#Suppress warnings...
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import os
print(os.getcwd())

C:\Users\fahad

In [3]:
os.listdir(os.getcwd())

['.android',
 '.AndroidStudio3.5',
 '.bash_history',
 '.conda',
 '.condarc',
 '.emulator_console_auth_token',
 '.gitconfig',
 '.gradle',
 '.IdeaIC2019.3',
 '.ipynb',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.python_history',
 '.spyder-py3',
 '.vscode',
 '3D Objects',
 'anaconda3',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'breast-cancer.csv',
 'car.csv',
 'Contacts',
 'Cookies',
 'Creative Cloud Files',
 'Documents',
 'Downloads',
 'E3B8562DC9D54D90A2DF1C66C1FDB932.TMP',
 'fahad.csv',
 'Favorites',
 'friends.csv',
 'friends_index_false.csv',
 'hayes-roth-names.csv',
 'hayes-roth.csv',
 'IntelGraphicsProfiles',
 'IRIS DATASET - SKLEARN TUTORIAL.ipynb',
 'K-MeansExample.ipynb',
 'Links',
 'Local Settings',
 'Machine Learning_Classification - Bank Dataset.ipynb',
 'Machine Learning_Regression - CA Housing Dataset.ipynb',
 'Market Basket Analysis_Apriori Algorithm_FR.ipynb',
 'Market Basket Introduction.ipynb',
 'Microsoft',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'my_array.npy',
 'nba_all_elo.csv',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{fd9a35db-49fe-11e9-aa2c-248a07783950}.TM.blf',
 'NTUSER.DAT{fd9a35db-49fe-11e9-aa2c-248a07783950}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{fd9a35db-49fe-11e9-aa2c-248a07783950}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'Numpy - Practice 1.ipynb',
 'numpy_tutorial.ipynb',
 'OneDrive',
 'Pandas - Practice 1.ipynb',
 'pandas_tutorial.ipynb',
 'Practice_Market Basket Analysis-Apriori Algorithm.ipynb',
 'presentations.ipynb',
 'PrintHood',
 'Programming Assignment 1 - CSE 6363-004_FAHAD UR RAHAMAN.ipynb',
 'Real or Not - NLP with Disaster Tweets.ipynb',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Text Analytics_FR.ipynb',
 'Untitled.ipynb',
 'venv',
 'Videos',
 'vulcancoin-part1.csv',
 'vulcancoin-part2.csv',
 'vulcancoin.ipynb',
 'wekafiles']

# DATA EXPLORATORY ANALYSIS OF MACHINE LEARNING DATASETS:
## "HAYES-ROTH"
## "CAR EVALUATION"
## "BREAST CANCER"

## Hayes-Roth Dataset [Data Set is Complete, No Missing Values]
#### Downloaded dataset from: "https://archive.ics.uci.edu/ml/machine-learning-databases/hayes-roth/"

In [4]:
df_hayes = pd.read_csv("hayes-roth.csv", names = ["name", "hobby", "age", "educational level", "marital status", "class"], header = None)
df_hayes.head(10)

    name  hobby  age  educational level  marital status  class
0   92.0    2.0  1.0                1.0             2.0    1.0
1   10.0    2.0  1.0                3.0             2.0    2.0
2   83.0    3.0  1.0                4.0             1.0    3.0
3   61.0    2.0  4.0                2.0             2.0    3.0
4  107.0    1.0  1.0                3.0             4.0    3.0
5  113.0    1.0  1.0                3.0             2.0    2.0
6   80.0    3.0  1.0                3.0             2.0    2.0
7  125.0    3.0  4.0                2.0             4.0    3.0
8   36.0    2.0  2.0                1.0             1.0    1.0
9  105.0    3.0  2.0                1.0             1.0    1.0

In [5]:
df_hayes.tail(10)

      name  hobby  age  educational level  marital status  class
122   71.0    3.0  1.0                2.0             2.0    2.0
123   43.0    3.0  2.0                2.0             4.0    3.0
124  131.0    2.0  3.0                1.0             3.0    1.0
125   17.0    2.0  1.0                1.0             2.0    1.0
126   12.0    3.0  4.0                1.0             3.0    3.0
127   44.0    1.0  1.0                4.0             3.0    3.0
128   40.0    2.0  1.0                2.0             1.0    1.0
129   90.0    1.0  2.0                1.0             2.0    2.0
130   21.0    1.0  2.0                2.0             1.0    2.0
131    9.0    3.0  1.0                1.0             2.0    1.0

In [6]:
df_hayes.columns

Index(['name', 'hobby', 'age', 'educational level', 'marital status', 'class'], dtype='object')

In [7]:
df_hayes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               132 non-null    float64
 1   hobby              132 non-null    float64
 2   age                132 non-null    float64
 3   educational level  132 non-null    float64
 4   marital status     132 non-null    float64
 5   class              132 non-null    float64
dtypes: float64(6)
memory usage: 6.3 KB

In [8]:
df_hayes.describe()

,name,hobby,age,educational level,marital status,class
count,132.000000,132.000000,132.000000,132.000000,132.000000,132.000000
mean,66.500000,2.000000,1.954545,1.954545,1.954545,1.840909
std,38.249183,0.819607,0.947988,0.947988,0.947988,0.769946
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,33.750000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,66.500000,2.000000,2.000000,2.000000,2.000000,2.000000
75%,99.250000,3.000000,2.000000,2.000000,2.000000,2.000000
max,132.000000,3.000000,4.000000,4.000000,4.000000,3.000000

In [9]:
df_hayes.name.nunique()

132

In [10]:
df_hayes.count()

name                 132
hobby                132
age                  132
educational level    132
marital status       132
class                132
dtype: int64

In [11]:
df_hayes["class"].value_counts()

2.0    51
1.0    51
3.0    30
Name: class, dtype: int64

## Car Evaluation Data Set [Dataset is Complete, No Missing Values]
#### Dataset is avaliable at: https://archive.ics.uci.edu/ml/machine-learning-databases/car/

In [12]:
df_car = pd.read_csv("car.csv", names = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "class_values"], header = None)
df_car.head(10)

  buying  maint doors persons lug_boot safety class_values
0  vhigh  vhigh     2       2    small    low        unacc
1  vhigh  vhigh     2       2    small    med        unacc
2  vhigh  vhigh     2       2    small   high        unacc
3  vhigh  vhigh     2       2      med    low        unacc
4  vhigh  vhigh     2       2      med    med        unacc
5  vhigh  vhigh     2       2      med   high        unacc
6  vhigh  vhigh     2       2      big    low        unacc
7  vhigh  vhigh     2       2      big    med        unacc
8  vhigh  vhigh     2       2      big   high        unacc
9  vhigh  vhigh     2       4    small    low        unacc

In [13]:
df_car.tail(10)

     buying maint  doors persons lug_boot safety class_values
1718    low   low  5more       4      big   high        vgood
1719    low   low  5more    more    small    low        unacc
1720    low   low  5more    more    small    med          acc
1721    low   low  5more    more    small   high         good
1722    low   low  5more    more      med    low        unacc
1723    low   low  5more    more      med    med         good
1724    low   low  5more    more      med   high        vgood
1725    low   low  5more    more      big    low        unacc
1726    low   low  5more    more      big    med         good
1727    low   low  5more    more      big   high        vgood

In [14]:
df_car.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety',
       'class_values'],
      dtype='object')

In [15]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   buying        1728 non-null   object
 1   maint         1728 non-null   object
 2   doors         1728 non-null   object
 3   persons       1728 non-null   object
 4   lug_boot      1728 non-null   object
 5   safety        1728 non-null   object
 6   class_values  1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB

In [16]:
df_car.describe()

       buying maint doors persons lug_boot safety class_values
count    1728  1728  1728    1728     1728   1728         1728
unique      4     4     4       3        3      3            4
top       med   med     3       4      med    med        unacc
freq      432   432   432     576      576    576         1210

In [17]:
df_car.count()

buying          1728
maint           1728
doors           1728
persons         1728
lug_boot        1728
safety          1728
class_values    1728
dtype: int64

In [18]:
df_car['class_values'].value_counts()

unacc    1210
acc       384
good       69
vgood      65
Name: class_values, dtype: int64

## Breast Cancer Data Set [Dataset is incomplete and contains missing values]
#### Dataset Available at: https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer/

In [19]:
df_breast_cancer = pd.read_csv("breast-cancer.csv", names = ["Class", "age", "menopause", "tumor-size", "inv-nodes", "node-caps", "deg-malig", "breast", "breast-quad", "irradiat"], header = None)
df_breast_cancer.head(15)

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
5,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,left,left_low,no
6,no-recurrence-events,50-59,premeno,25-29,0-2,no,2,left,left_low,no
7,no-recurrence-events,60-69,ge40,20-24,0-2,no,1,left,left_low,no
8,no-recurrence-events,40-49,premeno,50-54,0-2,no,2,left,left_low,no
9,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,left_up,no
10,no-recurrence-events,40-49,premeno,0-4,0-2,no,3,left,central,no
11,no-recurrence-events,50-59,ge40,25-29,0-2,no,2,left,left_low,no
12,no-recurrence-events,60-69,lt40,14-Oct,0-2,no,1,left,right_up,no
13,no-recurrence-events,50-59,ge40,25-29,0-2,no,3,left,right_up,no
14,no-recurrence-events,40-49,premeno,30-34,0-2,no,3,left,left_up,no

In [20]:
df_breast_cancer.tail(10)

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
276,recurrence-events,30-39,premeno,25-29,8-Jun,yes,3,left,right_low,yes
277,recurrence-events,60-69,ge40,14-Oct,8-Jun,yes,3,left,left_up,yes
278,recurrence-events,50-59,premeno,35-39,15-17,yes,3,right,right_up,no
279,recurrence-events,50-59,ge40,40-44,8-Jun,yes,3,left,left_low,yes
280,recurrence-events,50-59,ge40,40-44,8-Jun,yes,3,left,left_low,yes
281,recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
282,recurrence-events,30-39,premeno,20-24,0-2,no,3,left,left_up,yes
283,recurrence-events,60-69,ge40,20-24,0-2,no,1,right,left_up,no
284,recurrence-events,40-49,ge40,30-34,5-Mar,no,3,left,left_low,no
285,recurrence-events,50-59,ge40,30-34,5-Mar,no,3,left,left_low,no

In [21]:
df_breast_cancer.columns

Index(['Class', 'age', 'menopause', 'tumor-size', 'inv-nodes', 'node-caps',
       'deg-malig', 'breast', 'breast-quad', 'irradiat'],
      dtype='object')

In [22]:
df_breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Class        286 non-null    object
 1   age          286 non-null    object
 2   menopause    286 non-null    object
 3   tumor-size   286 non-null    object
 4   inv-nodes    286 non-null    object
 5   node-caps    286 non-null    object
 6   deg-malig    286 non-null    int64
 7   breast       286 non-null    object
 8   breast-quad  286 non-null    object
 9   irradiat     286 non-null    object
dtypes: int64(1), object(9)
memory usage: 22.5+ KB

In [23]:
df_breast_cancer.describe()

        deg-malig
count  286.000000
mean     2.048951
std      0.738217
min      1.000000
25%      2.000000
50%      2.000000
75%      3.000000
max      3.000000

In [24]:
df_breast_cancer.count()

Class          286
age            286
menopause      286
tumor-size     286
inv-nodes      286
node-caps      286
deg-malig      286
breast         286
breast-quad    286
irradiat       286
dtype: int64

In [25]:
df_breast_cancer['Class'].value_counts()

no-recurrence-events    201
recurrence-events        85
Name: Class, dtype: int64

In [26]:
import numpy as np
df_breast_cancer.loc[df_breast_cancer['breast-quad'] == "?", 'breast-quad'] = np.nan
df_breast_cancer.loc[df_breast_cancer['node-caps'] == "?", 'node-caps'] = np.nan
df_breast_cancer

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
...,...,...,...,...,...,...,...,...,...,...
281,recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
282,recurrence-events,30-39,premeno,20-24,0-2,no,3,left,left_up,yes
283,recurrence-events,60-69,ge40,20-24,0-2,no,1,right,left_up,no
284,recurrence-events,40-49,ge40,30-34,5-Mar,no,3,left,left_low,no
285,recurrence-events,50-59,ge40,30-34,5-Mar,no,3,left,left_low,no

In [27]:
df_breast_cancer.loc[:, df_breast_cancer.isnull().any()]

    node-caps breast-quad
0          no    left_low
1          no    right_up
2          no    left_low
3          no     left_up
4          no   right_low
..        ...         ...
281        no     left_up
282        no     left_up
283        no     left_up
284        no    left_low
285        no    left_low

[286 rows x 2 columns]

In [28]:
df_breast_cancer.isna().sum()

Class          0
age            0
menopause      0
tumor-size     0
inv-nodes      0
node-caps      8
deg-malig      0
breast         0
breast-quad    1
irradiat       0
dtype: int64

In [29]:
df_breast_cancer['tumor-size'] = df_breast_cancer['tumor-size'].replace(["14-Oct","9-May"],["10-14","5-9"])
df_breast_cancer

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
...,...,...,...,...,...,...,...,...,...,...
281,recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
282,recurrence-events,30-39,premeno,20-24,0-2,no,3,left,left_up,yes
283,recurrence-events,60-69,ge40,20-24,0-2,no,1,right,left_up,no
284,recurrence-events,40-49,ge40,30-34,5-Mar,no,3,left,left_low,no
285,recurrence-events,50-59,ge40,30-34,5-Mar,no,3,left,left_low,no

In [30]:
df_breast_cancer['inv-nodes'] = df_breast_cancer['inv-nodes'].replace(['5-Mar','8-Jun', '11-Sep', '14-Dec'],['3-5','6-8','9-11','12-14'])
df_breast_cancer

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
...,...,...,...,...,...,...,...,...,...,...
281,recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
282,recurrence-events,30-39,premeno,20-24,0-2,no,3,left,left_up,yes
283,recurrence-events,60-69,ge40,20-24,0-2,no,1,right,left_up,no
284,recurrence-events,40-49,ge40,30-34,3-5,no,3,left,left_low,no
285,recurrence-events,50-59,ge40,30-34,3-5,no,3,left,left_low,no

In [31]:
df_breast_cancer.head(20)

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
5,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,left,left_low,no
6,no-recurrence-events,50-59,premeno,25-29,0-2,no,2,left,left_low,no
7,no-recurrence-events,60-69,ge40,20-24,0-2,no,1,left,left_low,no
8,no-recurrence-events,40-49,premeno,50-54,0-2,no,2,left,left_low,no
9,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,left_up,no
10,no-recurrence-events,40-49,premeno,0-4,0-2,no,3,left,central,no
11,no-recurrence-events,50-59,ge40,25-29,0-2,no,2,left,left_low,no
12,no-recurrence-events,60-69,lt40,10-14,0-2,no,1,left,right_up,no
13,no-recurrence-events,50-59,ge40,25-29,0-2,no,3,left,right_up,no
14,no-recurrence-events,40-49,premeno,30-34,0-2,no,3,left,left_up,no
15,no-recurrence-events,60-69,lt40,30-34,0-2,no,1,left,left_low,no
16,no-recurrence-events,40-49,premeno,15-19,0-2,no,2,left,left_low,no
17,no-recurrence-events,50-59,premeno,30-34,0-2,no,3,left,left_low,no
18,no-recurrence-events,60-69,ge40,30-34,0-2,no,3,left,left_low,no
19,no-recurrence-events,50-59,ge40,30-34,0-2,no,1,right,right_up,no

In [32]:
df_breast_cancer.tail(10)

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
276,recurrence-events,30-39,premeno,25-29,6-8,yes,3,left,right_low,yes
277,recurrence-events,60-69,ge40,10-14,6-8,yes,3,left,left_up,yes
278,recurrence-events,50-59,premeno,35-39,15-17,yes,3,right,right_up,no
279,recurrence-events,50-59,ge40,40-44,6-8,yes,3,left,left_low,yes
280,recurrence-events,50-59,ge40,40-44,6-8,yes,3,left,left_low,yes
281,recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
282,recurrence-events,30-39,premeno,20-24,0-2,no,3,left,left_up,yes
283,recurrence-events,60-69,ge40,20-24,0-2,no,1,right,left_up,no
284,recurrence-events,40-49,ge40,30-34,3-5,no,3,left,left_low,no
285,recurrence-events,50-59,ge40,30-34,3-5,no,3,left,left_low,no

In [33]:
df_breast_cancer["node-caps"].value_counts()

no     222
yes     56
Name: node-caps, dtype: int64

In [34]:
df_breast_cancer["breast-quad"].value_counts()

left_low     110
left_up       97
right_up      33
right_low     24
central       21
Name: breast-quad, dtype: int64

In [35]:
mode = df_breast_cancer["breast-quad"].mode()
df_breast_cancer["breast-quad"] = df_breast_cancer["breast-quad"].fillna(mode[0])

In [36]:
mode1 = df_breast_cancer["node-caps"].mode()
df_breast_cancer["node-caps"] = df_breast_cancer["node-caps"].fillna(mode1[0])

In [37]:
df_breast_cancer.isna().sum()

Class          0
age            0
menopause      0
tumor-size     0
inv-nodes      0
node-caps      0
deg-malig      0
breast         0
breast-quad    0
irradiat       0
dtype: int64

In [38]:
df_breast_cancer.head(20)

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
5,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,left,left_low,no
6,no-recurrence-events,50-59,premeno,25-29,0-2,no,2,left,left_low,no
7,no-recurrence-events,60-69,ge40,20-24,0-2,no,1,left,left_low,no
8,no-recurrence-events,40-49,premeno,50-54,0-2,no,2,left,left_low,no
9,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,left_up,no
10,no-recurrence-events,40-49,premeno,0-4,0-2,no,3,left,central,no
11,no-recurrence-events,50-59,ge40,25-29,0-2,no,2,left,left_low,no
12,no-recurrence-events,60-69,lt40,10-14,0-2,no,1,left,right_up,no
13,no-recurrence-events,50-59,ge40,25-29,0-2,no,3,left,right_up,no
14,no-recurrence-events,40-49,premeno,30-34,0-2,no,3,left,left_up,no
15,no-recurrence-events,60-69,lt40,30-34,0-2,no,1,left,left_low,no
16,no-recurrence-events,40-49,premeno,15-19,0-2,no,2,left,left_low,no
17,no-recurrence-events,50-59,premeno,30-34,0-2,no,3,left,left_low,no
18,no-recurrence-events,60-69,ge40,30-34,0-2,no,3,left,left_low,no
19,no-recurrence-events,50-59,ge40,30-34,0-2,no,1,right,right_up,no

In [39]:
df_breast_cancer["node-caps"].value_counts()

no     230
yes     56
Name: node-caps, dtype: int64

In [40]:
df_breast_cancer["breast-quad"].value_counts()

left_low     111
left_up       97
right_up      33
right_low     24
central       21
Name: breast-quad, dtype: int64

In [41]:
dummy_df=pd.get_dummies(df_car, columns = ["buying","maint","doors","persons","lug_boot","safety","class_values"])
dummy_df

,buying_high,buying_low,buying_med,buying_vhigh,maint_high,maint_low,maint_med,maint_vhigh,doors_2,doors_3,...,lug_boot_big,lug_boot_med,lug_boot_small,safety_high,safety_low,safety_med,class_values_acc,class_values_good,class_values_unacc,class_values_vgood
0,0,0,0,1,0,0,0,1,1,0,...,0,0,1,0,1,0,0,0,1,0
1,0,0,0,1,0,0,0,1,1,0,...,0,0,1,0,0,1,0,0,1,0
2,0,0,0,1,0,0,0,1,1,0,...,0,0,1,1,0,0,0,0,1,0
3,0,0,0,1,0,0,0,1,1,0,...,0,1,0,0,1,0,0,0,1,0
4,0,0,0,1,0,0,0,1,1,0,...,0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,0,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,0
1724,0,1,0,0,0,1,0,0,0,0,...,0,1,0,1,0,0,0,0,0,1
1725,0,1,0,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
1726,0,1,0,0,0,1,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
1727,0,1,0,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,0,0,1

In [42]:
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   buying        1728 non-null   object
 1   maint         1728 non-null   object
 2   doors         1728 non-null   object
 3   persons       1728 non-null   object
 4   lug_boot      1728 non-null   object
 5   safety        1728 non-null   object
 6   class_values  1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB

# KNN Implementation, K-Fold CV from scratch - Hayes-Roth Dataset

### Enhancements performed by fine tuning the 'K' values and by calculating  different distance measures to achieve the best accuracy for our KNN Model on all 3 Datasets. Please see below the details of accuracy achieved in each case.

#### Dataset = "Hayes-Roth", K = 3, Distance = "Euclidean", Cross Validation = 10

In [43]:
# k-nearest neighbors on the Hayes-Roth Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['92', '2', '1', '1', '2', '1']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 
    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores
 
    # Calculate the Euclidean distance between two vectors
def euclidean_distance(row1, row2):
    distance = 0.0
    for i in range(len(row1)-1):
        distance += (row1[i] - row2[i])**2
    return sqrt(distance)
 
    # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = euclidean_distance(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
 
    # Test the kNN on the Hayes-Roth dataset
seed(1)
filename = 'hayes-roth.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 3
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores of 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Hayes-Roth Dataset using Euclidean Distance, K=3: %.3f%%' % (sum(scores)/float(len(scores))))

Scores of 10 Cross Validation Folds: [38.46153846153847, 30.76923076923077, 23.076923076923077, 30.76923076923077, 23.076923076923077, 30.76923076923077, 23.076923076923077, 53.84615384615385, 23.076923076923077, 46.15384615384615]
Mean Accuracy of Hayes-Roth Dataset using Euclidean Distance, K=3: 32.308%

#### Dataset = "Hayes-Roth", K = 5, Distance = "Hamming", Cross Validation = 10

In [44]:
# k-nearest neighbors on the Hayes-Roth Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['92', '2', '1', '1', '2', '1']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 
    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores

    # Calculate the Hamming distance between two vectors
def hamming_distance(row1, row2): 
    # Start with a distance of zero, and count up
    distance = 0
    # Loop over the indices of the string
    L = len(row1)
    for i in range(L):
        # Add 1 to the distance if these two characters are not equal
        if row1[i] != row2[i]:
            distance += 1
    # Return the final count of differences
    return distance
 
    # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = hamming_distance(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
 
    # Test the kNN on the Hayes-Roth dataset
seed(1)
filename = 'hayes-roth.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 5
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores of 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Hayes-Roth Dataset using Hamming Distance, K=5: %.3f%%' % (sum(scores)/float(len(scores))))

Scores of 10 Cross Validation Folds: [76.92307692307693, 53.84615384615385, 69.23076923076923, 69.23076923076923, 38.46153846153847, 69.23076923076923, 46.15384615384615, 38.46153846153847, 69.23076923076923, 76.92307692307693]
Mean Accuracy of Hayes-Roth Dataset using Hamming Distance, K=5: 60.769%

#### Dataset = "Hayes-Roth", K = 11, Distance = "Manhattan", Cross Validation = 10

In [45]:
# k-nearest neighbors on the Hayes-Roth Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['92', '2', '1', '1', '2', '1']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 
    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores

    # Calculate the Manhattan distance between two vectors
def manhattan_distance(row1, row2): 
    distance = 0
    # for each point, finding distance 
    # to rest of the point 
    for i in range(len(row1)-1): 
        for j in range(i+1,len(row1)-1): 
            distance += (abs(row1[i] - row1[j]) +
                        abs(row2[i] - row2[j]))
            return distance
 
    # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = manhattan_distance(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
 
    # Test the kNN on the Hayes-Roth dataset
seed(1)
filename = 'hayes-roth.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 11
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores fo 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Hayes-Roth Dataset using Manhattan Distance, K=11: %.3f%%' % (sum(scores)/float(len(scores))))

Scores fo 10 Cross Validation Folds: [30.76923076923077, 23.076923076923077, 30.76923076923077, 46.15384615384615, 53.84615384615385, 38.46153846153847, 53.84615384615385, 23.076923076923077, 38.46153846153847, 46.15384615384615]
Mean Accuracy of Hayes-Roth Dataset using Manhattan Distance, K=11: 38.462%

#### Dataset = "Hayes-Roth", K = 13, Distance = "Jaccard Similarity", Cross Validation = 10

In [46]:
# k-nearest neighbors on the Hayes-Roth Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['92', '2', '1', '1', '2', '1']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax

    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores

    # Calculate the Jaccard Similarity between two vectors
def jaccard_similarity(row1, row2):
  # Start with a distance of zero, and count up
    distance = 0.0
    # Loop over the indices of the string
    L = len(row1)
    for i in range(L):  
        intersection_cardinality = len(set.intersection(*[set(row1), set(row2)]))
        union_cardinality = len(set.union(*[set(row1), set(row2)]))
        distance += intersection_cardinality/float(union_cardinality)
    return distance
 
     # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = jaccard_similarity(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
     
    # Test the kNN on the Hayes-Roth dataset
seed(1)
filename = 'hayes-roth.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 13
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores of 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Hayes-Roth Dataset using Jaccard Similarity, K=13: %.3f%%' % (sum(scores)/float(len(scores))))

Scores of 10 Cross Validation Folds: [0.0, 0.0, 7.6923076923076925, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Mean Accuracy of Hayes-Roth Dataset using Jaccard Similarity, K=13: 0.769%

# KNN Implementation, K-Fold CV from scratch - Car Evaluation Dataset

#### Dataset = "Car Evaluation", K = 3, Distance = "Euclidean", Cross Validation = 10

In [47]:
# k-nearest neighbors on the Car Evaluation Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['vhigh', 'vhigh', '2', '2', 'small', 'low', 'unacc']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 
    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores
 
    # Calculate the Euclidean distance between two vectors
def euclidean_distance(row1, row2):
    distance = 0.0
    for i in range(len(row1)-1):
        distance += (row1[i] - row2[i])**2
    return sqrt(distance)
 
    # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = euclidean_distance(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
 
    # Test the kNN on the Car Evaluation dataset
seed(1)
filename = 'car.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)
str_column_to_int(dataset, 6)
for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 3
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores of 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Car Evaluation Dataset using Euclidean Distance, K=3: %.3f%%' % (sum(scores)/float(len(scores))))

Scores of 10 Cross Validation Folds: [90.69767441860465, 88.37209302325581, 89.53488372093024, 87.20930232558139, 90.69767441860465, 91.27906976744185, 81.3953488372093, 88.37209302325581, 86.04651162790698, 91.27906976744185]
Mean Accuracy of Car Evaluation Dataset using Euclidean Distance, K=3: 88.488%

#### Dataset = "Car Evaluation", K = 5, Distance = "Hamming", Cross Validation = 10

In [48]:
# k-nearest neighbors on the Car Evaluation Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['vhigh', 'vhigh', '2', '2', 'small', 'low', 'unacc']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 
    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores

    # Calculate the Hamming distance between two vectors
def hamming_distance(row1, row2): 
    # Start with a distance of zero, and count up
    distance = 0
    # Loop over the indices of the string
    L = len(row1)
    for i in range(L):
        # Add 1 to the distance if these two characters are not equal
        if row1[i] != row2[i]:
            distance += 1
    # Return the final count of differences
    return distance
 
    # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = hamming_distance(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
 
    # Test the kNN on the Car Evaluation dataset
seed(1)
filename = 'car.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)
str_column_to_int(dataset, 6)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 5
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores of 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Car Evaluation dataset using Hamming Distance, K=5: %.3f%%' % (sum(scores)/float(len(scores))))

Scores of 10 Cross Validation Folds: [86.04651162790698, 87.20930232558139, 86.04651162790698, 80.23255813953489, 87.20930232558139, 91.86046511627907, 77.90697674418605, 87.20930232558139, 84.30232558139535, 89.53488372093024]
Mean Accuracy of Car Evaluation dataset using Hamming Distance, K=5: 85.756%

#### Dataset = "Car Evaluation", K = 11, Distance = "Manhattan", Cross Validation = 10

In [49]:
# k-nearest neighbors on the Car Evaluation Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['vhigh', 'vhigh', '2', '2', 'small', 'low', 'unacc']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 
    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores

    # Calculate the Manhattan distance between two vectors
def manhattan_distance(row1, row2): 
    distance = 0
    # for each point, finding distance 
    # to rest of the point 
    for i in range(len(row1)-1): 
        for j in range(i+1,len(row1)-1): 
            distance += (abs(row1[i] - row1[j]) +
                        abs(row2[i] - row2[j]))
            return distance
 
    # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = manhattan_distance(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
 
    # Test the kNN on the Car Evaluation dataset
seed(1)
filename = 'car.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)
str_column_to_int(dataset, 6)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 11
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores fo 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Car Evaluation Dataset using Manhattan Distance, K=11: %.3f%%' % (sum(scores)/float(len(scores))))

Scores fo 10 Cross Validation Folds: [71.51162790697676, 68.02325581395348, 68.6046511627907, 66.86046511627907, 73.83720930232558, 70.34883720930233, 68.02325581395348, 72.09302325581395, 70.34883720930233, 69.76744186046511]
Mean Accuracy of Car Evaluation Dataset using Manhattan Distance, K=11: 69.942%

#### Dataset = "Car Evaluation", K = 7, Distance = "Jaccard Similarity", Cross Validation = 10

In [50]:
# k-nearest neighbors on the Car Evaluation Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['vhigh', 'vhigh', '2', '2', 'small', 'low', 'unacc']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax

    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores

    # Calculate the Jaccard Similarity between two vectors
def jaccard_similarity(row1, row2):
  # Start with a distance of zero, and count up
    distance = 0.0
    # Loop over the indices of the string
    L = len(row1)
    for i in range(L):  
        intersection_cardinality = len(set.intersection(*[set(row1), set(row2)]))
        union_cardinality = len(set.union(*[set(row1), set(row2)]))
        distance += intersection_cardinality/float(union_cardinality)
    return distance
 
     # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = jaccard_similarity(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
     
    # Test the kNN on the Car Evaluation dataset
seed(1)
filename = 'car.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)
str_column_to_int(dataset, 6)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 7
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores of 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Car Evaluation Dataset using Jaccard Similarity, K=7: %.3f%%' % (sum(scores)/float(len(scores))))

Scores of 10 Cross Validation Folds: [50.58139534883721, 45.348837209302324, 51.162790697674424, 54.65116279069767, 54.06976744186046, 54.65116279069767, 55.81395348837209, 58.139534883720934, 54.06976744186046, 47.093023255813954]
Mean Accuracy of Car Evaluation Dataset using Jaccard Similarity, K=7: 52.558%

# KNN Implementation, K-Fold CV from scratch - Breast Cancer Dataset

#### Dataset = "Breast Cancer", K = 11, Distance = "Euclidean", Cross Validation = 10

In [51]:
# k-nearest neighbors on the Breast Cancer Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['no-recurrence-events', '30-39', 'premeno', '30-34', '0-2', 'no', '3', 'left', 'left_low', 'no']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 
    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores
 
    # Calculate the Euclidean distance between two vectors
def euclidean_distance(row1, row2):
    distance = 0.0
    for i in range(len(row1)-1):
        distance += (row1[i] - row2[i])**2
    return sqrt(distance)
 
    # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = euclidean_distance(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
 
    # Test the kNN on the Breast Cancer dataset
seed(1)
filename = 'breast-cancer.csv'
dataset = load_csv(filename)
# convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)
str_column_to_int(dataset, 6)
str_column_to_int(dataset, 7)
str_column_to_int(dataset, 8)
str_column_to_int(dataset, 9)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

# evaluate algorithm
n_folds = 10
num_neighbors = 11
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores of 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Breast Cancer Dataset using Euclidean Distance, K=11: %.3f%%' % (sum(scores)/float(len(scores))))

Scores of 10 Cross Validation Folds: [85.71428571428571, 75.0, 57.14285714285714, 67.85714285714286, 75.0, 85.71428571428571, 89.28571428571429, 78.57142857142857, 85.71428571428571, 71.42857142857143]
Mean Accuracy of Breast Cancer Dataset using Euclidean Distance, K=11: 77.143%

#### Dataset = "Breast Cancer", K = 13, Distance = "Hamming", Cross Validation = 10

In [52]:
# k-nearest neighbors on the Breast Cancer Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['no-recurrence-events', '30-39', 'premeno', '30-34', '0-2', 'no', '3', 'left', 'left_low', 'no']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 
    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores

    # Calculate the Hamming distance between two vectors
def hamming_distance(row1, row2): 
    # Start with a distance of zero, and count up
    distance = 0
    # Loop over the indices of the string
    L = len(row1)
    for i in range(L):
        # Add 1 to the distance if these two characters are not equal
        if row1[i] != row2[i]:
            distance += 1
    # Return the final count of differences
    return distance
 
    # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = hamming_distance(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
 
    # Test the kNN on the Breast Cancer dataset
seed(1)
filename = 'breast-cancer.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)
str_column_to_int(dataset, 6)
str_column_to_int(dataset, 7)
str_column_to_int(dataset, 8)
str_column_to_int(dataset, 9)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 13
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores of 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Breast Cancer Dataset using Hamming Distance, K=13: %.3f%%' % (sum(scores)/float(len(scores))))

Scores of 10 Cross Validation Folds: [82.14285714285714, 78.57142857142857, 60.71428571428571, 64.28571428571429, 75.0, 96.42857142857143, 82.14285714285714, 82.14285714285714, 89.28571428571429, 67.85714285714286]
Mean Accuracy of Breast Cancer Dataset using Hamming Distance, K=13: 77.857%

#### Dataset = "Breast Cancer", K = 11, Distance = "Manhattan", Cross Validation = 10

In [53]:
# k-nearest neighbors on the Breast Cancer Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['no-recurrence-events', '30-39', 'premeno', '30-34', '0-2', 'no', '3', 'left', 'left_low', 'no']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 
    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores

    # Calculate the Manhattan distance between two vectors
def manhattan_distance(row1, row2): 
    distance = 0
    # for each point, finding distance 
    # to rest of the point 
    for i in range(len(row1)-1): 
        for j in range(i+1,len(row1)-1): 
            distance += (abs(row1[i] - row1[j]) +
                        abs(row2[i] - row2[j]))
            return distance
 
    # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = manhattan_distance(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
 
    # Test the kNN on the Breast Cancer dataset
seed(1)
filename = 'breast-cancer.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)
str_column_to_int(dataset, 6)
str_column_to_int(dataset, 7)
str_column_to_int(dataset, 8)
str_column_to_int(dataset, 9)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 11
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores fo 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Breast Cancer Dataset using Manhattan Distance, K=11: %.3f%%' % (sum(scores)/float(len(scores))))

Scores fo 10 Cross Validation Folds: [17.857142857142858, 71.42857142857143, 57.14285714285714, 64.28571428571429, 75.0, 89.28571428571429, 89.28571428571429, 82.14285714285714, 85.71428571428571, 67.85714285714286]
Mean Accuracy of Breast Cancer Dataset using Manhattan Distance, K=11: 70.000%

#### Dataset = "Breast Cancer", K = 15, Distance = "Jaccard Similarity", Cross Validation = 10

In [54]:
# k-nearest neighbors on the Breast Cancer Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
    # Load a CSV file
def load_csv(filename):
    dataset = list()
    with open(filename, 'r') as file:
        csv_reader = reader(file)
        for row in csv_reader:
            if not row:
                continue
            dataset.append(row)
            dataset[0]=['no-recurrence-events', '30-39', 'premeno', '30-34', '0-2', 'no', '3', 'left', 'left_low', 'no']
    return dataset
    
    # Convert string column to float
def str_column_to_float(dataset, column):
    for row in dataset:
        row[column] = float(row[column].strip())
 
    # Convert string column to integer
def str_column_to_int(dataset, column):
    class_values = [row[column] for row in dataset]
    unique = set(class_values)
    lookup = dict()
    for i, value in enumerate(unique):
        lookup[value] = i
    for row in dataset:
        row[column] = lookup[row[column]]
    return lookup
 
    # Find the min and max values for each column
def dataset_minmax(dataset):
    minmax = list()
    for i in range(len(dataset[0])):
        col_values = [row[i] for row in dataset]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax

    # Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
    for row in dataset:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
    # Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / n_folds)
    for _ in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 
    # Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0
 
    # Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
    folds = cross_validation_split(dataset, n_folds)
    scores = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predicted = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predicted)
        scores.append(accuracy)
    return scores

    # Calculate the Jaccard Similarity between two vectors
def jaccard_similarity(row1, row2):
  # Start with a distance of zero, and count up
    distance = 0.0
    # Loop over the indices of the string
    L = len(row1)
    for i in range(L):  
        intersection_cardinality = len(set.intersection(*[set(row1), set(row2)]))
        union_cardinality = len(set.union(*[set(row1), set(row2)]))
        distance += intersection_cardinality/float(union_cardinality)
    return distance
 
     # Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
    distances = list()
    for train_row in train:
        dist = jaccard_similarity(test_row, train_row)
        distances.append((train_row, dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors
 
    # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction
 
    # kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, num_neighbors)
        predictions.append(output)
    return(predictions)
     
    # Test the kNN on the Breast Cancer dataset
seed(1)
filename = 'breast-cancer.csv'
dataset = load_csv(filename)
    # convert class column to integers
str_column_to_int(dataset, 0)
str_column_to_int(dataset, 1)
str_column_to_int(dataset, 2)
str_column_to_int(dataset, 3)
str_column_to_int(dataset, 4)
str_column_to_int(dataset, 5)
str_column_to_int(dataset, 6)
str_column_to_int(dataset, 7)
str_column_to_int(dataset, 8)
str_column_to_int(dataset, 9)

for i in range(len(dataset[0])-1):
    str_column_to_int(dataset, i)

    # evaluate algorithm
n_folds = 10
num_neighbors = 15
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores of 10 Cross Validation Folds: %s' % scores)
print('Mean Accuracy of Breast Cancer Dataset using Jaccard Similarity, K=15: %.3f%%' % (sum(scores)/float(len(scores))))

Scores of 10 Cross Validation Folds: [64.28571428571429, 64.28571428571429, 57.14285714285714, 57.14285714285714, 64.28571428571429, 64.28571428571429, 71.42857142857143, 67.85714285714286, 57.14285714285714, 46.42857142857143]
Mean Accuracy of Breast Cancer Dataset using Jaccard Similarity, K=15: 61.429%